export enum EmployeeRole {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_HRM = 'ROLE_HRM',
  ROLE_PLANNER = 'ROLE_PLANNER',
  ROLE_EMPLOYEE = 'ROLE_EMPLOYEE',
  ROLE_PROJECT_LEADER = 'ROLE_PROJECT_LEADER',
  ROLE_ORDER_MANAGER = 'ROLE_ORDER_MANAGER',
  ROLE_LEAVE_REQUEST_MANAGER = 'ROLE_LEAVE_REQUEST_MANAGER',
  ROLE_WORKLOG_MANAGER = 'ROLE_WORKLOG_MANAGER',
  ROLE_WORKLOG_USER = 'ROLE_WORKLOG_USER',
  ROLE_BHV = 'ROLE_BHV',
}
