name: Default Workflow

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Check cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ubuntu-latest-node-modules-14-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: true

      - name: Build artifact
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist

  CreateRelease:
    name: Create Release
    if: "github.event.ref == 'refs/heads/main' && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist

      - name: Check cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ubuntu-latest-node-modules-12-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: true

      - name: Build & Save Artifacts
        run: |
          echo "Future goal: store artifacts"

      - name: Semantic release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  PostBuild:
    name: Post-Build job
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist

      - name: nop
        run: echo "no operation (nop)"
