name: Debug Workflow

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  #################################################################################
  # Environment: Preview Channels
  # Preview URL
  #################################################################################

  CreatePreview:
    name: Deploy Preview URL
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        app: ['krew-ui-angular', 'krew-website']
    env:
      PREVIEW_ID: ${{ matrix.app }}-PR-${{github.event.number}}
    environment:
      name: Preview Channels
      url: ${{ steps.action-hosting-deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        if: |
          contains(github.event.pull_request.labels.*.name, 'krew-website')
        run: echo "$GITHUB_CONTEXT"

      - name: Output debug
        if: |
          contains(github.event.pull_request.labels.*.name, 'app: ' + matrix.app')
        run: |
          echo 'Yes!'
          echo ${{ matrix.app }}
