name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  nighlty:
    name: Nightly build job

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest]
        app: [krew-ui-angular, krew-ui-svelte, krew-ui-react, krew-ui-vue]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint app ${{ matrix.app }}
        run: npm run lint -- ${{ matrix.app }}

      - name: Build app ${{ matrix.app }}
        run: npm run build -- ${{ matrix.app }} --configuration=production
