name: Default Release Workflow

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:
jobs:
  #################################################################################
  # Environment: -
  # Build & Lint
  #################################################################################

  BuildArtifacts:
    name: Build Artifacts job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        app: ['krew-ui-angular', 'krew-ui-svelte', 'krew-ui-react', 'krew-website', 'krew-crm-api']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ubuntu-latest-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build app ${{ matrix.app }}
        run: npm run build -- ${{ matrix.app }} --configuration=production

      - name: Display structure of dist folder
        run: ls -R
        working-directory: dist

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/apps

  #################################################################################
  # Environment: Preview Channels
  # Preview URL
  #################################################################################

  CreatePreview:
    name: Deploy Preview URL
    if: ${{ github.event_name == 'pull_request' }}
    needs: [BuildArtifacts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        app: ['krew-ui-angular', 'krew-ui-svelte', 'krew-ui-react', 'krew-website']
    env:
      PREVIEW_ID: ${{ matrix.app }}-PR-${{github.event.number}}
    environment:
      name: Preview Channels
      url: ${{ steps.action-hosting-deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
        if: |
          contains(github.event.pull_request.labels.*.name, format('app: {0}', matrix.app))

      - uses: actions/download-artifact@master
        if: |
          contains(github.event.pull_request.labels.*.name, format('app: {0}', matrix.app))
        with:
          name: artifacts
          path: dist/apps

      - name: Display structure of downloaded files
        if: |
          contains(github.event.pull_request.labels.*.name, format('app: {0}', matrix.app))
        run: ls -R
        working-directory: dist

      - name: Prepare deploy
        if: |
          contains(github.event.pull_request.labels.*.name, format('app: {0}', matrix.app))
        run: |
          cp -f apps/${{ matrix.app }}/server/.firebaserc ./
          cp -f apps/${{ matrix.app }}/server/firebase.json ./

      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: action-hosting-deploy
        if: |
          contains(github.event.pull_request.labels.*.name, format('app: {0}', matrix.app))
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: m4m-krew-dev
          channelId: ${{ env.PREVIEW_ID }}

  #################################################################################
  # Environment: Test
  # Deploy to Firebase
  #################################################################################

  DeployTest:
    name: Deploy to Test
    if: github.event.ref == 'refs/heads/develop'
    needs: [BuildArtifacts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        app: ['krew-ui-angular', 'krew-ui-svelte', 'krew-ui-react', 'krew-website']
    environment:
      name: Test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist/apps

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - name: Prepare deploy
        run: |
          cp -f apps/${{ matrix.app }}/server/.firebaserc ./
          cp -f apps/${{ matrix.app }}/server/firebase.json ./

      - name: Deploy ${{ matrix.app }} to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: action-hosting-deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: m4m-krew-dev
          channelId: live

  #################################################################################
  # Environment: Production
  # Releasing
  #################################################################################

  CreateRelease:
    name: Release to GitHub Releases
    if: "github.event.ref == 'refs/heads/main' && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    needs: [BuildArtifacts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: false

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ubuntu-latest-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: true

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist/apps

      - name: Prepare artifacts
        run: |
          mkdir -p ../../artifacts
          zip -r -X ../../artifacts/artifacts.zip .
        working-directory: dist/apps

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  #################################################################################
  # Environment: Production
  # Deploy to Firebase
  #################################################################################

  DeployProd:
    name: Deploy to Producton
    if: github.event.ref == 'refs/heads/main'
    needs: [CreateRelease]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        app: ['krew-ui-angular', 'krew-ui-svelte', 'krew-ui-react', 'krew-website']
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist/apps

      - name: Prepare deploy
        run: |
          cp -f apps/${{ matrix.app }}/server/.firebaserc ./
          cp -f apps/${{ matrix.app }}/server/firebase.json ./

      - uses: microsoft/variable-substitution@v1
        with:
          files: '.firebaserc'
        env:
          targets.m4m-krew-dev.hosting.krew-ui-angular.0: '${{ secrets.FIREBASE_HOSTING_TARGET_KREW_UI_ANGULAR }}'
          targets.m4m-krew-dev.hosting.krew-ui-react.0: '${{ secrets.FIREBASE_HOSTING_TARGET_KREW_UI_REACT }}'
          targets.m4m-krew-dev.hosting.krew-ui-svelte.0: '${{ secrets.FIREBASE_HOSTING_TARGET_KREW_UI_SVELTE }}'
          targets.m4m-krew-dev.hosting.krew-ui-vue.0: '${{ secrets.FIREBASE_HOSTING_TARGET_KREW_UI_VUE }}'
          targets.m4m-krew-dev.hosting.krew-website.0: '${{ secrets.FIREBASE_HOSTING_TARGET_KREW_WEBSITE }}'

      - name: Deploy ${{ matrix.app }} to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: action-hosting-deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
